# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeBase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeBase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  pod 'GoogleSignIn'

  pod 'FacebookCore'
  pod 'FBSDKLoginKit'
  pod 'FacebookShare'

  pod 'Alamofire', '~> 4.5'

  target 'HomeBaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
